baseURL = "http://example.org/"
languageCode = "en-us"
title = "Toto"
theme = "my_theme"
themesDir = "./themes"
paginate = 4

[outputs]
    page = ["html", "json"]
    section = ["html", "json"]
    home = ["html", "json"]

